---
title: "Homework 3"
author: "Yavuz Delen"
date: "4/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```


```{r}
loblolly_pheno <- read.csv("data/DATA_rootnum_age10_rootnum.csv", header = TRUE, stringsAsFactors = FALSE)
#View(loblolly_pheno)


geno_data <- "https://jyanglab.com/img/data/Snp_Data.csv"

loblolly_geno <- read.csv(geno_data, header=TRUE, stringsAsFactors = FALSE)
head(loblolly_geno)
#View(loblolly_geno)

dim(loblolly_pheno) #926 4
dim(loblolly_geno) #926 4854
loblolly_geno[1:5, 1:5]
```


## Remove missing phenotypes
```{r, eval=FALSE}
is.na(loblolly_pheno$Derregressed_BV)
#sum(is.na(loblolly_pheno$Derregressed_BV)) #1
na.index <-  which(is.na(loblolly_pheno$Derregressed_BV))
#head(loblolly_pheno[na.index,])


# length(na.index) #1
loblolly_pheno <- loblolly_pheno[-na.index, ]


# Keep genotypes for these remaining lines
loblolly_geno <- loblolly_geno[loblolly_geno$Genotype %in% loblolly_pheno$Genotype, ]

# phenotypes 
y <- loblolly_pheno$Derregressed_BV
y <- matrix(y, ncol=1)
y

# markers 
loblolly_geno <- loblolly_geno[,-1] 
loblolly_geno[loblolly_geno == -9] <- NA

```


# SNP quality control
### Missingness and MAF

```{r, eval=FALSE, echo=TRUE}
# missing rate
missing <- apply(loblolly_geno, 2, function(x){sum(is.na(x))/length(x)})
head(missing)
#hist(missing)


# minor allele frequency
maf <- apply(loblolly_geno, 2, function(x){
  frq <- mean(x, na.rm=TRUE)/2
  return(ifelse(frq > 0.5, 1-frq, frq))
})
```

#### Plot the results
```{r, eval=FALSE, echo=TRUE}
hist(missing, breaks=100, col="blue", xlab="SNP Missing rate")
hist(maf, breaks=100, col="blue", xlab="Minor Allele Freq")
```


# SNP quality control

Removing SNPs with high missing rate (missingness > 0.2) and low MAF (MAF < 0.05)

```{r, eval=FALSE, echo=TRUE}
idx1 <- which(missing > 0.2) #154
idx2 <- which(maf < 0.05) #1647
idx <- unique(c(idx1, idx2)) #1784

loblolly_geno2 <- loblolly_geno[, -idx]
dim(loblolly_geno2)  #925 3074
```

